version: '3.8'

services:
  web:
    build: .
    container_name: calseva_web
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/calsevav2
      - SECRET_KEY=calseva_docker_super_secret_key_2026
      - FIREBASE_PROJECT_ID=calseva-2026
      - FIREBASE_MESSAGING_SENDER_ID=104417696551
      - FIREBASE_VAPID_KEY=BG9hLohg7jKRV_NC6NxVLCYr2J136Qldq8PQFMJ1ogwBuQBEs70EwJzINX3hrInBXtK_K_jcLEAj05mwKCLzRC4
      - ADMIN_EMPLOYEE_IDS=12345,09112
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: calseva_db
    restart: always
    environment:
      - POSTGRES_DB=calsevav2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d calsevav2"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
